allow-lan: true
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- alterId: 0
  cipher: auto
  name: kr
  port: 45579
  server: 211.54.247.9
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: a43d4fc7-a22d-4398-c818-2c89c6c7ba27
- cipher: chacha20-ietf-poly1305
  name: Singapore-07">
  password: AHyDyR
  port: 56047
  server: fzx.6pzfwf.com
  type: ss
- alterId: 0
  cipher: auto
  name: ebnlkf9t
  network: ws
  port: 30443
  server: hinetkvm001.nmcloud.cc
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 2a381434-0cbc-4aae-8551-7c9535ee5ed2
  ws-opts:
    headers:
      Host: ''
    path: /
- alterId: 0
  cipher: auto
  name: V1-台湾 多台负载均衡 中继F 1.5x
  network: ws
  port: 64088
  server: in06.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in06.my1188.org
    path: /biteb
- cipher: chacha20-ietf-poly1305
  name: Japan-02
  password: AHyDyR
  port: 56032
  server: fzx.6pzfwf.com
  type: ss
- alterId: 0
  cipher: auto
  name: liunxdo-ud0976md
  port: 11606
  server: hd.cc.990777.xyz
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: b557b631-c447-42ee-8099-f688fcaf4e06
- alterId: 0
  cipher: auto
  name: V1-台湾 多台负载均衡 中继A 1.5x
  network: ws
  port: 64088
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-台湾 多台负载均衡 中继D 1.5x
  network: ws
  port: 64088
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-新加坡 多台负载均衡 中继D 1.5x
  network: ws
  port: 64087
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-德国01 CDN 中继 1.5x
  network: ws
  port: 64084
  server: in05.my1188.org
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-台湾 多台负载均衡 中继B 1.5x
  network: ws
  port: 64088
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /biteb
- cipher: chacha20-ietf-poly1305
  name: Taiwan-06
  password: AHyDyR
  port: 56026
  server: fzx.6pzfwf.com
  type: ss
- alterId: 0
  cipher: auto
  name: V1-新加坡 多台负载均衡 中继B 1.5x
  network: ws
  port: 64087
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-俄罗斯01 中继A 1.2x
  network: ws
  port: 64071
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-俄罗斯01 中继B 1.2x
  network: ws
  port: 64071
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-新加坡 多台负载均衡 中继A 1.5x
  network: ws
  port: 64087
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-台湾 多台负载均衡 中继C 1.5x
  network: ws
  port: 64088
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-俄罗斯01 中继D 1.2x
  network: ws
  port: 64071
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-新加坡 多台负载均衡 中继F 1.5x
  network: ws
  port: 64087
  server: in06.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in06.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-新加坡 多台负载均衡 中继C 1.5x
  network: ws
  port: 64087
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-日本 多台负载均衡 中继A 1.5x
  network: ws
  port: 64086
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-日本 多台负载均衡 中继F 1.5x
  network: ws
  port: 64086
  server: in06.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in06.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-日本 多台负载均衡 中继D 1.5x
  network: ws
  port: 64086
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-俄罗斯01 中继C 1.2x
  network: ws
  port: 64071
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-美国01 中继A | 1.5x
  network: ws
  port: 64014
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-香港 多台负载均衡 中继C | 2x
  network: ws
  port: 64078
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-台湾99 Hinet直连 速度随缘 0.5x
  network: ws
  port: 2096
  server: tw99-hinet.myn1des.com
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: tw99-hinet.myn1des.com
    path: /
- alterId: 0
  cipher: auto
  name: V1-日本 多台负载均衡 中继C 1.5x
  network: ws
  port: 64086
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-美国01 中继D | 1.5x
  network: ws
  port: 64014
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-香港 多台负载均衡 中继B | 2x
  network: ws
  port: 64078
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-美国01 中继C | 1.5x
  network: ws
  port: 64014
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V1-香港 多台负载均衡 中继D | 2x
  network: ws
  port: 64078
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-香港 多台负载均衡 中继A | 2x
  network: ws
  port: 64078
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-英国01 CDN 中继 1.5x
  network: ws
  port: 64021
  server: in05.my1188.org
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-荷兰01 CDN 中继 1.3x
  network: ws
  port: 64062
  server: in05.my1188.org
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-香港HKT03 CDN 中继 2x
  network: ws
  port: 64082
  server: in05.my1188.org
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-香港HKT02 CDN 中继 2x
  network: ws
  port: 64081
  server: in05.my1188.org
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V1-美国01 中继B | 1.5x
  network: ws
  port: 64014
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V2-印度01 中继E 1.7x
  network: ws
  port: 64051
  server: in05.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /hls
- alterId: 0
  cipher: auto
  name: V1-日本 多台负载均衡 中继B 1.5x
  network: ws
  port: 64086
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /biteb
- alterId: 0
  cipher: auto
  name: V2-印度01 中继B 1.7x
  network: ws
  port: 64051
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /hls
- alterId: 0
  cipher: auto
  name: V2-土耳其01 中继E | 2x
  network: ws
  port: 64028
  server: in05.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V2-印度01 中继A 1.7x
  network: ws
  port: 64051
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /hls
- alterId: 0
  cipher: auto
  name: V2-土耳其01 中继A | 2x
  network: ws
  port: 64028
  server: in01.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in01.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V2-土耳其01 中继C | 2x
  network: ws
  port: 64028
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V2-土耳其01 中继B | 2x
  network: ws
  port: 64028
  server: in02.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in02.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V2-印度01 中继D 1.7x
  network: ws
  port: 64051
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /hls
- alterId: 0
  cipher: auto
  name: V2-印度01 中继C 1.7x
  network: ws
  port: 64051
  server: in03.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in03.my1188.org
    path: /hls
- alterId: 0
  cipher: auto
  name: V2-土耳其01 中继D | 2x
  network: ws
  port: 64028
  server: in04.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in04.my1188.org
    path: /
- alterId: 0
  cipher: auto
  name: V2-台湾 多台负载均衡 中继E 1.5x
  network: ws
  port: 64088
  server: in05.my1188.org
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 531e6c4b-2f5f-363f-8556-3531b85422d5
  ws-opts:
    headers:
      Host: in05.my1188.org
    path: /biteb
proxy-groups:
- name: 🚀 节点选择
  proxies:
  - ♻️ 自动选择
  - 🎯 全球直连
  - kr
  - Singapore-07">
  - ebnlkf9t
  - V1-台湾 多台负载均衡 中继F 1.5x
  - Japan-02
  - liunxdo-ud0976md
  - V1-台湾 多台负载均衡 中继A 1.5x
  - V1-台湾 多台负载均衡 中继D 1.5x
  - V1-新加坡 多台负载均衡 中继D 1.5x
  - V1-德国01 CDN 中继 1.5x
  - V1-台湾 多台负载均衡 中继B 1.5x
  - Taiwan-06
  - V1-新加坡 多台负载均衡 中继B 1.5x
  - V1-俄罗斯01 中继A 1.2x
  - V1-俄罗斯01 中继B 1.2x
  - V1-新加坡 多台负载均衡 中继A 1.5x
  - V1-台湾 多台负载均衡 中继C 1.5x
  - V1-俄罗斯01 中继D 1.2x
  - V1-新加坡 多台负载均衡 中继F 1.5x
  - V1-新加坡 多台负载均衡 中继C 1.5x
  - V1-日本 多台负载均衡 中继A 1.5x
  - V1-日本 多台负载均衡 中继F 1.5x
  - V1-日本 多台负载均衡 中继D 1.5x
  - V1-俄罗斯01 中继C 1.2x
  - V1-美国01 中继A | 1.5x
  - V1-香港 多台负载均衡 中继C | 2x
  - V1-台湾99 Hinet直连 速度随缘 0.5x
  - V1-日本 多台负载均衡 中继C 1.5x
  - V1-美国01 中继D | 1.5x
  - V1-香港 多台负载均衡 中继B | 2x
  - V1-美国01 中继C | 1.5x
  - V1-香港 多台负载均衡 中继D | 2x
  - V1-香港 多台负载均衡 中继A | 2x
  - V1-英国01 CDN 中继 1.5x
  - V1-荷兰01 CDN 中继 1.3x
  - V1-香港HKT03 CDN 中继 2x
  - V1-香港HKT02 CDN 中继 2x
  - V1-美国01 中继B | 1.5x
  - V2-印度01 中继E 1.7x
  - V1-日本 多台负载均衡 中继B 1.5x
  - V2-印度01 中继B 1.7x
  - V2-土耳其01 中继E | 2x
  - V2-印度01 中继A 1.7x
  - V2-土耳其01 中继A | 2x
  - V2-土耳其01 中继C | 2x
  - V2-土耳其01 中继B | 2x
  - V2-印度01 中继D 1.7x
  - V2-印度01 中继C 1.7x
  - V2-土耳其01 中继D | 2x
  - V2-台湾 多台负载均衡 中继E 1.5x
  type: select
- interval: 300
  name: ♻️ 自动选择
  proxies:
  - kr
  - Singapore-07">
  - ebnlkf9t
  - V1-台湾 多台负载均衡 中继F 1.5x
  - Japan-02
  - liunxdo-ud0976md
  - V1-台湾 多台负载均衡 中继A 1.5x
  - V1-台湾 多台负载均衡 中继D 1.5x
  - V1-新加坡 多台负载均衡 中继D 1.5x
  - V1-德国01 CDN 中继 1.5x
  - V1-台湾 多台负载均衡 中继B 1.5x
  - Taiwan-06
  - V1-新加坡 多台负载均衡 中继B 1.5x
  - V1-俄罗斯01 中继A 1.2x
  - V1-俄罗斯01 中继B 1.2x
  - V1-新加坡 多台负载均衡 中继A 1.5x
  - V1-台湾 多台负载均衡 中继C 1.5x
  - V1-俄罗斯01 中继D 1.2x
  - V1-新加坡 多台负载均衡 中继F 1.5x
  - V1-新加坡 多台负载均衡 中继C 1.5x
  - V1-日本 多台负载均衡 中继A 1.5x
  - V1-日本 多台负载均衡 中继F 1.5x
  - V1-日本 多台负载均衡 中继D 1.5x
  - V1-俄罗斯01 中继C 1.2x
  - V1-美国01 中继A | 1.5x
  - V1-香港 多台负载均衡 中继C | 2x
  - V1-台湾99 Hinet直连 速度随缘 0.5x
  - V1-日本 多台负载均衡 中继C 1.5x
  - V1-美国01 中继D | 1.5x
  - V1-香港 多台负载均衡 中继B | 2x
  - V1-美国01 中继C | 1.5x
  - V1-香港 多台负载均衡 中继D | 2x
  - V1-香港 多台负载均衡 中继A | 2x
  - V1-英国01 CDN 中继 1.5x
  - V1-荷兰01 CDN 中继 1.3x
  - V1-香港HKT03 CDN 中继 2x
  - V1-香港HKT02 CDN 中继 2x
  - V1-美国01 中继B | 1.5x
  - V2-印度01 中继E 1.7x
  - V1-日本 多台负载均衡 中继B 1.5x
  - V2-印度01 中继B 1.7x
  - V2-土耳其01 中继E | 2x
  - V2-印度01 中继A 1.7x
  - V2-土耳其01 中继A | 2x
  - V2-土耳其01 中继C | 2x
  - V2-土耳其01 中继B | 2x
  - V2-印度01 中继D 1.7x
  - V2-印度01 中继C 1.7x
  - V2-土耳其01 中继D | 2x
  - V2-台湾 多台负载均衡 中继E 1.5x
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: 🎯 全球直连
  proxies:
  - DIRECT
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- GEOIP,CN,🎯 全球直连
- MATCH,🚀 节点选择
socks-port: 7891
